{% set name = "libvpx" %}
{% set version = "1.11.0" %}
{% set p = "m2-" if win else "" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://download.videolan.org/contrib/vpx/libvpx-{{ version }}.tar.gz
  sha256: 965e51c91ad9851e2337aebcc0f517440c637c506f3a03948062e3d5ea129a83

build:
  number: 0
  skip: True  # [win or s390x]
  run_exports:
    # new so names and compatibility changes on minor version
    # https://abi-laboratory.pro/tracker/timeline/libvpx/
    - {{ pin_subpackage('libvpx', max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - posix                     # [win]
    - {{ p }}git
    - {{ p }}make
    - {{ p }}libtool
    - m2w64-toolchain          # [win]
    - yasm
  run:
    - m2w64-gcc-libs           # [win]

test:
  requires:
    - conda-build
  commands:
    - test -f ${PREFIX}/lib/libvpx${SHLIB_EXT}
    - ${PREFIX}/bin/vpxenc --help  # [build_platform == target_platform]
    - ${PREFIX}/bin/vpxdec --help  # [build_platform == target_platform]
    - conda inspect linkages -p $PREFIX libvpx    # [not win]
    - conda inspect objects -p $PREFIX libvpx     # [osx]

about:
  home: https://www.webmproject.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-quality, open video format for the web
  description: |
    libvpx is a free software video codec library from
    Google and the Alliance for Open Media (AOMedia).
    It serves as the reference software implementation for
    the video coding formats VP8 and VP9, and for AV1 a
    special fork named libaom that was stripped of
    backwards compatibility.
  doc_url: http://www.webmproject.org/vp9/
  dev_url: https://chromium.googlesource.com/webm/libvpx

extra:
  recipe-maintainers:
    - matthiasdiener
